"""followers

Revision ID: 220ffb08b8cf
Revises: 16783ccd8c61
Create Date: 2025-10-17 12:28:50.206886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220ffb08b8cf'
down_revision = '16783ccd8c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
